# Generated by Django 4.2.7 on 2024-10-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='academico',
            fields=[
                ('cedula', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('prestamos', models.CharField(default=0, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='administrativo',
            fields=[
                ('cedula', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('prestamos', models.CharField(default=0, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='estudiante',
            fields=[
                ('cedula', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('año', models.CharField(max_length=1)),
                ('seccion', models.CharField(max_length=1)),
                ('prestamos', models.CharField(default=0, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='libro',
            fields=[
                ('codigolibro', models.CharField(default=1, max_length=25, primary_key=True, serialize=False)),
                ('autor', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=35)),
                ('materia', models.CharField(max_length=20)),
                ('año', models.CharField(max_length=20)),
                ('cantidad', models.CharField(default=0, max_length=6)),
                ('cantidadPres', models.CharField(default=0, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='prestamo',
            fields=[
                ('codigo', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('codigolibro', models.CharField(default=1, max_length=25)),
                ('autor', models.CharField(default='', max_length=20)),
                ('titulo', models.CharField(default='', max_length=20)),
                ('usuario', models.CharField(choices=[('1', 'Estudiante'), ('2', 'Academico'), ('3', 'Administrativo')], default='Estudiante', max_length=20)),
                ('nombre', models.CharField(default='', max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('cedula', models.CharField(max_length=8)),
                ('bibliotecaria', models.CharField(max_length=40)),
                ('tipoPrestamo', models.CharField(default='', max_length=20)),
                ('tipoUsuario', models.CharField(default='', max_length=20)),
                ('fechaInicial', models.CharField(default='', max_length=8)),
                ('fechaFinal', models.CharField(default='', max_length=8)),
                ('observaciones', models.CharField(default='', max_length=40)),
            ],
        ),
    ]
